name: Test
on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.run/**'
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable', 1.20.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -race -v -count=1 -covermode=atomic -coverprofile=test.coverage ./...

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./test.coverage
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
